name: 'Record Release'
description: 'Record a deployment or release to Groo Ops Dashboard'
author: 'groo.dev'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  token:
    description: 'Groo Ops API token. Required for init and finalize modes. Not needed for upload-only mode.'
    required: false
  environment:
    description: 'Deployment environment (production, staging, development). Required for init mode, auto-loaded from session in finalize mode.'
    required: false
  version:
    description: 'Explicit semantic version (e.g., 1.2.3). If not provided, uses bump.'
    required: false
  bump:
    description: 'Version bump type (major, minor, patch). Default: patch'
    required: false
    default: 'patch'
  commit-hash:
    description: 'Git commit SHA. Default: github.sha'
    required: false
  commit-message:
    description: 'Commit message. Default: from github event'
    required: false
  deployed-by:
    description: 'Deployer identifier. Default: github-actions'
    required: false
    default: 'github-actions'
  api-url:
    description: 'Groo Ops API URL'
    required: false
    default: 'https://ops.groo.dev/v1'
  dry-run:
    description: 'Init mode for multi-job workflows. Gets next version and saves session for finalize job.'
    required: false
    default: 'false'
  get-version:
    description: 'Get current deployed version without making changes.'
    required: false
    default: 'false'
  skip-github-release:
    description: 'Skip creating GitHub release.'
    required: false
    default: 'false'
  release-prefix:
    description: 'Prefix for GitHub release tag. If set, tag is {prefix}-v{version}. If not set, tag is v{version}.'
    required: false
  github-token:
    description: 'GitHub token for creating releases.'
    required: false
    default: ${{ github.token }}
  body:
    description: 'Release notes content.'
    required: false
  body-file:
    description: 'Path to file containing release notes.'
    required: false
  draft:
    description: 'Create release as draft.'
    required: false
    default: 'false'
  prerelease:
    description: 'Mark release as prerelease.'
    required: false
    default: 'false'
  artifacts:
    description: 'Glob patterns for files to upload as release assets (one per line). In multi-job workflows, use this in build jobs to upload artifacts - they are automatically collected in finalize job.'
    required: false

outputs:
  version:
    description: 'The recorded/current version'
  id:
    description: 'The deployment record ID'
  deployed-at:
    description: 'Deployment timestamp (get-version mode only)'
  commit-hash:
    description: 'Commit hash of deployment (get-version mode only)'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/post.js'
  post-if: success()
